[package]
authors = [
  "Lucio Franco <luciofranco14@gmail.com>",
  "Rafael Lemos <flemos.rafael.dev@gmail.com>"
]
categories = ["web-programming", "network-programming", "asynchronous"]
description = """
A collection of useful protobuf types that can be used with `tonic`.
"""
documentation = "https://docs.rs/tonic-types/0.12.2"
edition = "2021"
homepage = { workspace = true }
keywords = ["rpc", "grpc", "protobuf"]
license = "MIT AND Apache-2.0"
name = "tonic-types"
readme = "README.md"
repository = { workspace = true }
version = { workspace = true }

[dependencies]
prost = "0.13"
prost-types = "0.13"
tonic = { version = "0.12", path = "../tonic", default-features = false }

[package.metadata.cargo_check_external_types]
allowed_external_types = [
  "tonic::*",

  # not major released
  "prost::*",
  "prost_types::*",
]
