[package]
name = "codegen"
edition = "2021"
publish = false

[dependencies]
tempfile = "3.8.0"
tonic-build = {path = "../tonic-build", default-features = false, features = ["prost", "cleanup-markdown"]}
